version: "3.8"

services:
    app:
        build: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
        environment:
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_KEY=base64:xcKrUtzqHXpM51zD/YPHQAILxPtNVtyAJ/cETF4r5CY=
            - APP_DEBUG=true
            - APP_URL=http://localhost:8080
            - DB_CONNECTION=pgsql
            - DB_HOST=aws-1-ap-southeast-1.pooler.supabase.com
            - DB_PORT=5432
            - DB_DATABASE=postgres
            - DB_USERNAME=postgres.bscddyfdbwceljvjvbro
            - DB_PASSWORD=pjoHCtcFje2sCItg
            - LOG_CHANNEL=stack
            - LOG_LEVEL=debug
            - CACHE_DRIVER=file
            - SESSION_DRIVER=file
            - QUEUE_CONNECTION=sync
# No local database needed - using Supabase
